image: docker:19.03.12

pipelines:
  default:
    - parallel:
        - step:
            runs-on:
              - self.hosted
              - linux
            name: Build and Test
            services:
              - docker
            image: gradle:7.6.4-jdk17-focal
            caches:
              - gradle
            script:
              - export TESTCONTAINERS_RYUK_DISABLED=true
              - ./gradlew build
            after-script:
              - pipe: atlassian/checkstyle-report:0.3.0
            artifacts:
              - build/libs/sockbowl-game-0.0.1-SNAPSHOT.jar
        - step:
            runs-on:
              - self.hosted
              - linux
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.5.1
    - step:
        runs-on:
          - self.hosted
          - linux
        name: Publish to S3
        script:
          - pipe: atlassian/aws-s3-deploy:1.6.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: 'your-bucket-name'
              LOCAL_PATH: 'build/libs/sockbowl-game-0.0.1-SNAPSHOT.jar'
              S3_PATH: 'sockbowl-game-prod.jar'

definitions:
  services:
    docker:
      image: docker:19.03.12-dind
      privileged: true
